[build]
  publish = "public"
  command = '''
    npm install && \
    pip install -r requirements.txt && \
    python3 preprocess.py --source_path content --target_path content --target_attachment_path static && \
    mkdir -p assets/indices && \
    echo '{"index":{"links":{},"backlinks":{},"tags":{}},"links":[],"tags":[]}' > assets/indices/linkIndex.json && \
    for file in content/*.md; do \
      filename=$(basename "$file" .md); \
      links=$(grep -o '\[\[[^]]*\]\]' "$file" | sed 's/\[\[\([^|]*\)|.*\]\]/\1/g; s/\[\[\([^]]*\)\]\]/\1/g' | sort -u); \
      if [ ! -z "$links" ]; then \
        json_links=$(echo "$links" | jq -R . | jq -s .); \
        tmp=$(mktemp); \
        jq --arg key "/$filename" --argjson arr "$json_links" '.index.links[$key] = $arr' assets/indices/linkIndex.json > "$tmp" && mv "$tmp" assets/indices/linkIndex.json; \
      fi; \
    done && \
    python3 postprocess.py && \
    curl -L https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_linux-amd64.tar.gz | tar -xz && \
    ./hugo --gc --minify'''

[build.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO111MODULE = "on"
  NODE_VERSION = "18.16.1"
  NPM_FLAGS = "--version"
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
